# The URL the site will be built for
base_url = "https://simondalvai.org"
title = "Simon Dalvai"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

theme = "magic-box"

# Default author
author = "Simon Dalvai"

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-light", filename = "light-code.css" },
  { theme = "solarized-dark", filename = "dark-code.css" },
]

[extra]
icon = "me.webp"

# links
links.github = "https://github.com/dulvui"
links.codeberg = "https://codeberg.org/dulvui"
links.itchio = "https://simondalvai.itch.io/"
links.mastodon = "https://mastodon.social/@dulvui"
links.reddit = "https://reddit.com/user/dulvui"
links.linkedin = "https://www.linkedin.com/in/simon-dalvai"
links.githubsponsors = "https://github.com/sponsors/dulvui"
links.liberapay = "https://liberapay.com/dulvui"
links.paypal = "https://paypal.me/simondalvai"
links.hetzner = "https://hetzner.cloud/?ref=bavTO3Qc2Kar"


email = "info@simondalvai.org"

# privacy policy
privacy_policy_updated = "2023-06-10"
repo_github = "https://github.com/dulvui/simondalvai.org"
repo_codeberg = "https://codeberg.org/dulvui/simondalvai.org"
